//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.10 at 02:00:45 PM EET 
//


package com.haad;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityID" minOccurs="0"/>
 *         &lt;element name="Start" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityStart"/>
 *         &lt;element name="Type" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityType"/>
 *         &lt;element name="Code" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityCode"/>
 *         &lt;element name="Quantity" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityQuantity"/>
 *         &lt;element name="Net" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityNet"/>
 *         &lt;element name="OrderingClinician" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityOrderingClinician" minOccurs="0"/>
 *         &lt;element name="Clinician" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityClinician" minOccurs="0"/>
 *         &lt;element name="PriorAuthorizationID" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityPriorAuthorizationID" minOccurs="0"/>
 *         &lt;element name="VAT" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityVAT" minOccurs="0"/>
 *         &lt;element name="VATPercent" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityVATPercent" minOccurs="0"/>
 *         &lt;element name="Observation" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Type" type="{http://www.haad.ae/DataDictionary/CommonTypes}ObservationType"/>
 *                   &lt;element name="Code" type="{http://www.haad.ae/DataDictionary/CommonTypes}ObservationCode"/>
 *                   &lt;element name="Value" type="{http://www.haad.ae/DataDictionary/CommonTypes}ObservationValue" minOccurs="0"/>
 *                   &lt;element name="ValueType" type="{http://www.haad.ae/DataDictionary/CommonTypes}ObservationValueType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "start",
    "type",
    "code",
    "quantity",
    "net",
    "orderingClinician",
    "clinician",
    "priorAuthorizationID",
    "vat",
    "vatPercent",
    "observation"
})
@Entity
@Table(name = "activity")
public class Activity implements Serializable{
    
    private static final long serialVersionUID = 1L;
    @Id
    @NotNull
    @Column(name = "activity_id", nullable = false)
    @GeneratedValue(strategy = GenerationType.AUTO)
    @XmlTransient 
    private Long activity_id;

    @Column(name = "id")
    @XmlElement(name = "ID")
    protected String id;
    
    @Column(name = "start")
    @XmlElement(name = "Start", required = true)
    protected String start;
    
    @Column(name = "type")
    @XmlElement(name = "Type", required = true)
    protected BigInteger type;
    
    @Column(name = "code")
    @XmlElement(name = "Code", required = true)
    protected String code;
    
    @Column(name = "quantity")
    @XmlElement(name = "Quantity")
    protected float quantity;
    
    @Column(name = "net")
    @XmlElement(name = "Net")
    protected float net;
    
    @Column(name = "orderingClinician")
    @XmlElement(name = "OrderingClinician")
    protected String orderingClinician;
    
    @Column(name = "clinician")
    @XmlElement(name = "Clinician")
    protected String clinician;
    
    @Column(name = "priorAuthorizationID")
    @XmlElement(name = "PriorAuthorizationID")
    protected String priorAuthorizationID;
    
    @Column(name = "vat")
    @XmlElement(name = "VAT")
    protected Float vat;
    
    @Column(name = "vatPercent")
    @XmlElement(name = "VATPercent")
    protected Float vatPercent;
    
    @OneToMany(mappedBy = "activity", cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
    @XmlElement(name = "Observation")
    protected List<Observation> observation;
    
    @JoinColumn(name = "claim_id", referencedColumnName = "claim_id")
    @ManyToOne
    @XmlTransient
    private Claim claim;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStart(String value) {
        this.start = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setType(BigInteger value) {
        this.type = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public float getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(float value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the net property.
     * 
     */
    public float getNet() {
        return net;
    }

    /**
     * Sets the value of the net property.
     * 
     */
    public void setNet(float value) {
        this.net = value;
    }

    /**
     * Gets the value of the orderingClinician property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderingClinician() {
        return orderingClinician;
    }

    /**
     * Sets the value of the orderingClinician property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderingClinician(String value) {
        this.orderingClinician = value;
    }

    /**
     * Gets the value of the clinician property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClinician() {
        return clinician;
    }

    /**
     * Sets the value of the clinician property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClinician(String value) {
        this.clinician = value;
    }

    /**
     * Gets the value of the priorAuthorizationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriorAuthorizationID() {
        return priorAuthorizationID;
    }

    /**
     * Sets the value of the priorAuthorizationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriorAuthorizationID(String value) {
        this.priorAuthorizationID = value;
    }

    /**
     * Gets the value of the vat property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getVAT() {
        return vat;
    }

    /**
     * Sets the value of the vat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVAT(Float value) {
        this.vat = value;
    }

    /**
     * Gets the value of the vatPercent property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getVATPercent() {
        return vatPercent;
    }

    /**
     * Sets the value of the vatPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVATPercent(Float value) {
        this.vatPercent = value;
    }

    /**
     * Gets the value of the observation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the observation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObservation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Observation }
     * 
     * 
     */
    public List<Observation> getObservation() {
        if (observation == null) {
            observation = new ArrayList<Observation>();
        }
        return this.observation;
    }

    public Long getActivity_id() {
        return activity_id;
    }

    public void setActivity_id(Long activity_id) {
        this.activity_id = activity_id;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Float getVat() {
        return vat;
    }

    public void setVat(Float vat) {
        this.vat = vat;
    }

    public Float getVatPercent() {
        return vatPercent;
    }

    public void setVatPercent(Float vatPercent) {
        this.vatPercent = vatPercent;
    }

    public Claim getClaim() {
        return claim;
    }

    public void setClaim(Claim claim) {
        this.claim = claim;
    }
    
    
    

}
