//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.10 at 02:00:45 PM EET 
//


package com.haad;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuthorizationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AuthorizationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Eligibility"/>
 *     &lt;enumeration value="Authorization"/>
 *     &lt;enumeration value="Cancellation"/>
 *     &lt;enumeration value="Extension"/>
 *     &lt;enumeration value="Status Inquiry"/>
 *     &lt;enumeration value="Prescription"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AuthorizationType", namespace = "http://www.haad.ae/DataDictionary/CommonTypes")
@XmlEnum
public enum AuthorizationType {

    @XmlEnumValue("Eligibility")
    ELIGIBILITY("Eligibility"),
    @XmlEnumValue("Authorization")
    AUTHORIZATION("Authorization"),
    @XmlEnumValue("Cancellation")
    CANCELLATION("Cancellation"),
    @XmlEnumValue("Extension")
    EXTENSION("Extension"),
    @XmlEnumValue("Status Inquiry")
    STATUS_INQUIRY("Status Inquiry"),
    @XmlEnumValue("Prescription")
    PRESCRIPTION("Prescription");
    private final String value;

    AuthorizationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AuthorizationType fromValue(String v) {
        for (AuthorizationType c: AuthorizationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
