//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.10 at 02:00:45 PM EET 
//


package com.haad;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.haad.ae/DataDictionary/CommonTypes}ClaimID"/>
 *         &lt;element name="IDPayer" type="{http://www.haad.ae/DataDictionary/CommonTypes}ClaimIDPayer" minOccurs="0"/>
 *         &lt;element name="MemberID" type="{http://www.haad.ae/DataDictionary/CommonTypes}ClaimMemberID" minOccurs="0"/>
 *         &lt;element name="PayerID" type="{http://www.haad.ae/DataDictionary/CommonTypes}ClaimPayerID"/>
 *         &lt;element name="ProviderID" type="{http://www.haad.ae/DataDictionary/CommonTypes}ClaimProviderID"/>
 *         &lt;element name="EmiratesIDNumber" type="{http://www.haad.ae/DataDictionary/CommonTypes}ClaimEmiratesIDNumber"/>
 *         &lt;element name="Gross" type="{http://www.haad.ae/DataDictionary/CommonTypes}ClaimGross"/>
 *         &lt;element name="PatientShare" type="{http://www.haad.ae/DataDictionary/CommonTypes}ClaimPatientShare"/>
 *         &lt;element name="Net" type="{http://www.haad.ae/DataDictionary/CommonTypes}ClaimNet"/>
 *         &lt;element name="VAT" type="{http://www.haad.ae/DataDictionary/CommonTypes}ClaimVAT" minOccurs="0"/>
 *         &lt;element name="Encounter" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FacilityID" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterFacilityID"/>
 *                   &lt;element name="Type" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterType"/>
 *                   &lt;element name="PatientID" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterPatientID"/>
 *                   &lt;element name="EligibilityIDPayer" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterEligibilityIDPayer" minOccurs="0"/>
 *                   &lt;element name="Start" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterStart"/>
 *                   &lt;element name="End" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterEnd" minOccurs="0"/>
 *                   &lt;element name="StartType" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterStartType" minOccurs="0"/>
 *                   &lt;element name="EndType" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterEndType" minOccurs="0"/>
 *                   &lt;element name="TransferSource" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterTransferSource" minOccurs="0"/>
 *                   &lt;element name="TransferDestination" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterTransferDestination" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Diagnosis" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Type" type="{http://www.haad.ae/DataDictionary/CommonTypes}DiagnosisType"/>
 *                   &lt;element name="Code" type="{http://www.haad.ae/DataDictionary/CommonTypes}DiagnosisCode"/>
 *                   &lt;element name="DxInfo" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Type" type="{http://www.haad.ae/DataDictionary/CommonTypes}DxInfoType"/>
 *                             &lt;element name="Code" type="{http://www.haad.ae/DataDictionary/CommonTypes}DxInfoCode"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Activity" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ID" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityID" minOccurs="0"/>
 *                   &lt;element name="Start" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityStart"/>
 *                   &lt;element name="Type" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityType"/>
 *                   &lt;element name="Code" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityCode"/>
 *                   &lt;element name="Quantity" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityQuantity"/>
 *                   &lt;element name="Net" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityNet"/>
 *                   &lt;element name="OrderingClinician" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityOrderingClinician" minOccurs="0"/>
 *                   &lt;element name="Clinician" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityClinician" minOccurs="0"/>
 *                   &lt;element name="PriorAuthorizationID" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityPriorAuthorizationID" minOccurs="0"/>
 *                   &lt;element name="VAT" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityVAT" minOccurs="0"/>
 *                   &lt;element name="VATPercent" type="{http://www.haad.ae/DataDictionary/CommonTypes}ActivityVATPercent" minOccurs="0"/>
 *                   &lt;element name="Observation" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Type" type="{http://www.haad.ae/DataDictionary/CommonTypes}ObservationType"/>
 *                             &lt;element name="Code" type="{http://www.haad.ae/DataDictionary/CommonTypes}ObservationCode"/>
 *                             &lt;element name="Value" type="{http://www.haad.ae/DataDictionary/CommonTypes}ObservationValue" minOccurs="0"/>
 *                             &lt;element name="ValueType" type="{http://www.haad.ae/DataDictionary/CommonTypes}ObservationValueType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Resubmission" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Type" type="{http://www.haad.ae/DataDictionary/CommonTypes}ResubmissionType"/>
 *                   &lt;element name="Comment" type="{http://www.haad.ae/DataDictionary/CommonTypes}ResubmissionComment"/>
 *                   &lt;element name="Attachment" type="{http://www.haad.ae/DataDictionary/CommonTypes}ResubmissionAttachments" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Contract" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PackageName" type="{http://www.haad.ae/DataDictionary/CommonTypes}ContractPackageName" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "idPayer",
    "memberID",
    "payerID",
    "providerID",
    "emiratesIDNumber",
    "gross",
    "patientShare",
    "net",
    "vat",
    "encounter",
    "diagnosis",
    "activity",
    "resubmission",
    "contract"
})
@Entity
@Table(name = "claim")
public class Claim implements Serializable{

    private static final long serialVersionUID = 1L;
    @Id
    @NotNull
    @Column(name = "claim_id", nullable = false)
    @GeneratedValue(strategy = GenerationType.AUTO)
    @XmlTransient 
    private Long claim_id;
    
    
    @Column(name = "id")
    @XmlElement(name = "ID", required = true)
    protected String id;
    
    @Column(name = "idPayer")
    @XmlElement(name = "IDPayer")
    protected String idPayer;
    
    @Column(name = "memberID")
    @XmlElement(name = "MemberID")
    protected String memberID;
    
    @Column(name = "payerID")
    @XmlElement(name = "PayerID", required = true)
    protected String payerID;
    
    @Column(name = "providerID")
    @XmlElement(name = "ProviderID", required = true)
    protected String providerID;
    
    @Column(name = "emiratesIDNumber")
    @XmlElement(name = "EmiratesIDNumber", required = true)
    protected String emiratesIDNumber;
    
    @Column(name = "gross")
    @XmlElement(name = "Gross")
    protected float gross;
    
    @Column(name = "patientShare")
    @XmlElement(name = "PatientShare")
    protected float patientShare;
    
    @Column(name = "net")
    @XmlElement(name = "Net")
    protected float net;
    
    @Column(name = "vat")
    @XmlElement(name = "VAT")
    protected Float vat;
    
    @OneToMany(mappedBy = "claim", cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
    @XmlElement(name = "Encounter", required = true)
    protected List<Encounter> encounter;
    
    @OneToMany(mappedBy = "claim", cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
    @XmlElement(name = "Diagnosis", required = true)
    protected List<Diagnosis> diagnosis;
    
    @OneToMany(mappedBy = "claim", cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
    @XmlElement(name = "Activity", required = true)
    protected List<Activity> activity;
    
    @OneToOne(mappedBy = "claim", cascade = CascadeType.PERSIST)
    @XmlElement(name = "Resubmission")
    protected Resubmission resubmission;
    
    @OneToOne(mappedBy = "claim", cascade = CascadeType.PERSIST)
    @XmlElement(name = "Contract")
    protected Contract contract;
    
    
    @JoinColumn(name = "claim_submission_id", referencedColumnName = "ID")
    @ManyToOne
    @XmlTransient
    private ClaimSubmission claimSubmission;
    

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the idPayer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDPayer() {
        return idPayer;
    }

    /**
     * Sets the value of the idPayer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDPayer(String value) {
        this.idPayer = value;
    }

    /**
     * Gets the value of the memberID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberID() {
        return memberID;
    }

    /**
     * Sets the value of the memberID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberID(String value) {
        this.memberID = value;
    }

    /**
     * Gets the value of the payerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerID() {
        return payerID;
    }

    /**
     * Sets the value of the payerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerID(String value) {
        this.payerID = value;
    }

    /**
     * Gets the value of the providerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderID() {
        return providerID;
    }

    /**
     * Sets the value of the providerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderID(String value) {
        this.providerID = value;
    }

    /**
     * Gets the value of the emiratesIDNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmiratesIDNumber() {
        return emiratesIDNumber;
    }

    /**
     * Sets the value of the emiratesIDNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmiratesIDNumber(String value) {
        this.emiratesIDNumber = value;
    }

    /**
     * Gets the value of the gross property.
     * 
     */
    public float getGross() {
        return gross;
    }

    /**
     * Sets the value of the gross property.
     * 
     */
    public void setGross(float value) {
        this.gross = value;
    }

    /**
     * Gets the value of the patientShare property.
     * 
     */
    public float getPatientShare() {
        return patientShare;
    }

    /**
     * Sets the value of the patientShare property.
     * 
     */
    public void setPatientShare(float value) {
        this.patientShare = value;
    }

    /**
     * Gets the value of the net property.
     * 
     */
    public float getNet() {
        return net;
    }

    /**
     * Sets the value of the net property.
     * 
     */
    public void setNet(float value) {
        this.net = value;
    }

    /**
     * Gets the value of the vat property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getVAT() {
        return vat;
    }

    /**
     * Sets the value of the vat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVAT(Float value) {
        this.vat = value;
    }

    /**
     * Gets the value of the encounter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the encounter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEncounter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Encounter }
     * 
     * 
     */
    public List<Encounter> getEncounter() {
        if (encounter == null) {
            encounter = new ArrayList<Encounter>();
        }
        return this.encounter;
    }

    /**
     * Gets the value of the diagnosis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diagnosis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiagnosis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Diagnosis }
     * 
     * 
     */
    public List<Diagnosis> getDiagnosis() {
        if (diagnosis == null) {
            diagnosis = new ArrayList<Diagnosis>();
        }
        return this.diagnosis;
    }

    /**
     * Gets the value of the activity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Activity }
     * 
     * 
     */
    public List<Activity> getActivity() {
        if (activity == null) {
            activity = new ArrayList<Activity>();
        }
        return this.activity;
    }

    /**
     * Gets the value of the resubmission property.
     * 
     * @return
     *     possible object is
     *     {@link Resubmission }
     *     
     */
    public Resubmission getResubmission() {
        return resubmission;
    }

    /**
     * Sets the value of the resubmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resubmission }
     *     
     */
    public void setResubmission(Resubmission value) {
        this.resubmission = value;
    }

    /**
     * Gets the value of the contract property.
     * 
     * @return
     *     possible object is
     *     {@link Contract }
     *     
     */
    public Contract getContract() {
        return contract;
    }

    /**
     * Sets the value of the contract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contract }
     *     
     */
    public void setContract(Contract value) {
        this.contract = value;
    }

    public Long getClaim_id() {
        return claim_id;
    }

    public void setClaim_id(Long claim_id) {
        this.claim_id = claim_id;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getIdPayer() {
        return idPayer;
    }

    public void setIdPayer(String idPayer) {
        this.idPayer = idPayer;
    }

    public Float getVat() {
        return vat;
    }

    public void setVat(Float vat) {
        this.vat = vat;
    }

    public ClaimSubmission getClaimSubmission() {
        return claimSubmission;
    }

    public void setClaimSubmission(ClaimSubmission claimSubmission) {
        this.claimSubmission = claimSubmission;
    }

    
}
