//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.10 at 02:00:45 PM EET 
//


package com.haad;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DiagnosisType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DiagnosisType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Principal"/>
 *     &lt;enumeration value="Secondary"/>
 *     &lt;enumeration value="Admitting"/>
 *     &lt;enumeration value="ReasonForVisit"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DiagnosisType", namespace = "http://www.haad.ae/DataDictionary/CommonTypes")
@XmlEnum
public enum DiagnosisType {

    @XmlEnumValue("Principal")
    PRINCIPAL("Principal"),
    @XmlEnumValue("Secondary")
    SECONDARY("Secondary"),
    @XmlEnumValue("Admitting")
    ADMITTING("Admitting"),
    @XmlEnumValue("ReasonForVisit")
    REASON_FOR_VISIT("ReasonForVisit");
    private final String value;

    DiagnosisType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DiagnosisType fromValue(String v) {
        for (DiagnosisType c: DiagnosisType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
