//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.10 at 02:00:45 PM EET 
//


package com.haad;

import java.io.Serializable;
import java.math.BigInteger;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FacilityID" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterFacilityID"/>
 *         &lt;element name="Type" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterType"/>
 *         &lt;element name="PatientID" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterPatientID"/>
 *         &lt;element name="EligibilityIDPayer" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterEligibilityIDPayer" minOccurs="0"/>
 *         &lt;element name="Start" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterStart"/>
 *         &lt;element name="End" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterEnd" minOccurs="0"/>
 *         &lt;element name="StartType" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterStartType" minOccurs="0"/>
 *         &lt;element name="EndType" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterEndType" minOccurs="0"/>
 *         &lt;element name="TransferSource" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterTransferSource" minOccurs="0"/>
 *         &lt;element name="TransferDestination" type="{http://www.haad.ae/DataDictionary/CommonTypes}EncounterTransferDestination" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "facilityID",
    "type",
    "patientID",
    "eligibilityIDPayer",
    "start",
    "end",
    "startType",
    "endType",
    "transferSource",
    "transferDestination"
})
@Entity
@Table(name = "encounter")
public class Encounter implements Serializable{
    
    private static final long serialVersionUID = 1L;
    @Id
    @NotNull
    @Column(name = "id", nullable = false)
    @GeneratedValue(strategy = GenerationType.AUTO)
    @XmlTransient 
    private Long id;

    @Column(name = "facilityID")
    @XmlElement(name = "FacilityID", required = true)
    protected String facilityID;
    
    @Column(name = "type")
    @XmlElement(name = "Type", required = true)
    protected BigInteger type;
    
    @Column(name = "patientID")
    @XmlElement(name = "PatientID", required = true)
    protected String patientID;
    
    @Column(name = "eligibilityIDPayer")
    @XmlElement(name = "EligibilityIDPayer")
    protected String eligibilityIDPayer;
    
    @Column(name = "startAt")
    @XmlElement(name = "Start", required = true)
    protected String start;
    
    @Column(name = "endAt")
    @XmlElement(name = "End")
    protected String end;
    
    @Column(name = "startType")
    @XmlElement(name = "StartType")
    protected BigInteger startType;
    
    @Column(name = "endType")
    @XmlElement(name = "EndType")
    protected BigInteger endType;
    
    @Column(name = "transferSource")
    @XmlElement(name = "TransferSource")
    protected String transferSource;
    
    @Column(name = "transferDestination")
    @XmlElement(name = "TransferDestination")
    protected String transferDestination;
    
    @JoinColumn(name = "claim_id", referencedColumnName = "claim_id")
    @ManyToOne
    @XmlTransient
    private Claim claim;
    /**
     * Gets the value of the facilityID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacilityID() {
        return facilityID;
    }

    /**
     * Sets the value of the facilityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacilityID(String value) {
        this.facilityID = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setType(BigInteger value) {
        this.type = value;
    }

    /**
     * Gets the value of the patientID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientID() {
        return patientID;
    }

    /**
     * Sets the value of the patientID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientID(String value) {
        this.patientID = value;
    }

    /**
     * Gets the value of the eligibilityIDPayer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEligibilityIDPayer() {
        return eligibilityIDPayer;
    }

    /**
     * Sets the value of the eligibilityIDPayer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEligibilityIDPayer(String value) {
        this.eligibilityIDPayer = value;
    }

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStart(String value) {
        this.start = value;
    }

    /**
     * Gets the value of the end property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnd(String value) {
        this.end = value;
    }

    /**
     * Gets the value of the startType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStartType() {
        return startType;
    }

    /**
     * Sets the value of the startType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStartType(BigInteger value) {
        this.startType = value;
    }

    /**
     * Gets the value of the endType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEndType() {
        return endType;
    }

    /**
     * Sets the value of the endType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEndType(BigInteger value) {
        this.endType = value;
    }

    /**
     * Gets the value of the transferSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferSource() {
        return transferSource;
    }

    /**
     * Sets the value of the transferSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferSource(String value) {
        this.transferSource = value;
    }

    /**
     * Gets the value of the transferDestination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferDestination() {
        return transferDestination;
    }

    /**
     * Sets the value of the transferDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferDestination(String value) {
        this.transferDestination = value;
    }

    public Claim getClaim() {
        return claim;
    }

    public void setClaim(Claim claim) {
        this.claim = claim;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    

}
