//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.10 at 02:00:45 PM EET 
//


package com.haad;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HeaderDispositionFlag.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HeaderDispositionFlag">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PRODUCTION"/>
 *     &lt;enumeration value="TEST"/>
 *     &lt;enumeration value="PTE_SUBMIT"/>
 *     &lt;enumeration value="PTE_VALIDATE_ONLY"/>
 *     &lt;enumeration value="PTE_RESPONSE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HeaderDispositionFlag", namespace = "http://www.haad.ae/DataDictionary/CommonTypes")
@XmlEnum
public enum HeaderDispositionFlag {

    PRODUCTION,
    TEST,
    PTE_SUBMIT,
    PTE_VALIDATE_ONLY,
    PTE_RESPONSE;

    public String value() {
        return name();
    }

    public static HeaderDispositionFlag fromValue(String v) {
        return valueOf(v);
    }

}
