//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.10 at 02:00:45 PM EET 
//


package com.haad;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MemberRelation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MemberRelation">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Principal"/>
 *     &lt;enumeration value="Spouse"/>
 *     &lt;enumeration value="Parent"/>
 *     &lt;enumeration value="Child"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MemberRelation", namespace = "http://www.haad.ae/DataDictionary/CommonTypes")
@XmlEnum
public enum MemberRelation {

    @XmlEnumValue("Principal")
    PRINCIPAL("Principal"),
    @XmlEnumValue("Spouse")
    SPOUSE("Spouse"),
    @XmlEnumValue("Parent")
    PARENT("Parent"),
    @XmlEnumValue("Child")
    CHILD("Child"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    MemberRelation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MemberRelation fromValue(String v) {
        for (MemberRelation c: MemberRelation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
