//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.10 at 02:00:45 PM EET 
//


package com.haad;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObservationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ObservationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CPT"/>
 *     &lt;enumeration value="HL7v3 Native"/>
 *     &lt;enumeration value="LOINC"/>
 *     &lt;enumeration value="SNOMED CT"/>
 *     &lt;enumeration value="Text"/>
 *     &lt;enumeration value="File"/>
 *     &lt;enumeration value="Flags"/>
 *     &lt;enumeration value="Universal Dental"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ObservationType", namespace = "http://www.haad.ae/DataDictionary/CommonTypes")
@XmlEnum
public enum ObservationType {

    CPT("CPT"),
    @XmlEnumValue("HL7v3 Native")
    HL_7_V_3_NATIVE("HL7v3 Native"),
    LOINC("LOINC"),
    @XmlEnumValue("SNOMED CT")
    SNOMED_CT("SNOMED CT"),
    @XmlEnumValue("Text")
    TEXT("Text"),
    @XmlEnumValue("File")
    FILE("File"),
    @XmlEnumValue("Flags")
    FLAGS("Flags"),
    @XmlEnumValue("Universal Dental")
    UNIVERSAL_DENTAL("Universal Dental");
    private final String value;

    ObservationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ObservationType fromValue(String v) {
        for (ObservationType c: ObservationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
