//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.10 at 02:00:45 PM EET 
//


package com.haad;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResubmissionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ResubmissionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="correction"/>
 *     &lt;enumeration value="internal complaint"/>
 *     &lt;enumeration value="legacy"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ResubmissionType", namespace = "http://www.haad.ae/DataDictionary/CommonTypes")
@XmlEnum
public enum ResubmissionType {

    @XmlEnumValue("correction")
    CORRECTION("correction"),
    @XmlEnumValue("internal complaint")
    INTERNAL_COMPLAINT("internal complaint"),
    @XmlEnumValue("legacy")
    LEGACY("legacy");
    private final String value;

    ResubmissionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ResubmissionType fromValue(String v) {
        for (ResubmissionType c: ResubmissionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
